### ISSUE TITLE
The HTML doesn't render

### ISSUE THREAD

**Issue by matuskalas** [edamontology/edamontology.org#1]
Big thanks @inkuzmin for reporting!

@hmenager @veitveit @inkuzmin If you'll have a bit of time, could you please inspect the page source in your browser, and see if you can find the issue? I'll look at it tonight (unless you fix it in the meantime :P :D) 1000000000 THANKS!

The body content is Markdown-to-HTML as you can see.

**Comment by hmenager** [comment]
What happens is that the js that takes care of converting the md contents into HTML was loaded from an external site, and has now disappeared completely. I can't find it anywhere:
[the hosting domain](https://aplib.github.io) is dead. If you have a local backup for this library it would come in handy, because otherwise we'll have to find an alternative...

**Comment by inkuzmin** [comment]
This seems to be the reason indeed.

I found one copy of the `document.min.js` [here](https://github.com/diev/aplib-docs). Not sure if it's an obsolete version or not, the repository hasn't been updated for about 5 years. It seems to work in my browser though.

Please note that as the script is minified I didn't really inspect it on any kind of exploits.

**Comment by hmenager** [comment]
Ok, it is probably an obsolete version, but since it works, I think the best way forward would be to:
1- as a temporary solution copy this file in the https://github.com/edamontology/edamontology.org repo and use the local version in the HTML, then redeploy to edamontology.org.
2- find another solution, more stable, very soon, to replace this way of generating the pages.

**Comment by hmenager** [comment]
thoughts @inkuzmin @matuskalas ?

**Comment by hmenager** [comment]
ok, I uploaded a "local" version of the js and it seems to be working again. Now @matuskalas we only need you to transfer this to the edamontology.org website.

**Comment by joncison** [comment]
We should probably migrate to GitHub pages soon ... e.g. I managed to produce https://bio-tools.github.io/Tool-Information-Standard/ without much heartache ...

**Comment by matuskalas** [comment]
Many thanks, uploaded now.

2-_e.g._ we could find another md2html or find|create a nice css and use standard html (it's anyway already full of html inside the md), even completely w/o js as this part of the site static anyway.

**Comment by inkuzmin** [comment]
@hmenager awesome, it works now!

**Comment by inkuzmin** [comment]
> find another solution, more stable, very soon, to replace this way of generating the pages.

Do you think it would make sense to take it as a mini-project for the ongoing BCC2020 event?
